import Head from "next/head";
import Navigation from "../components/header/navigation";
import Header from "../components/header/legal-header";
import ContactBlock from "../components/contact-block";
import Footer from "../components/footer";
import LegalSidebarContact from "../components/legal-sidebar-contact";
import MobileNavigation from "../components/header/mobile-navigation";

export default function Post() {
  return (
    <div>
      <Head>
        <title>Cookie Policy | Livalta Newsroom</title>
      </Head>
      <div
        className="w-full bg-container"
        style={{
          backgroundImage: "url(/images/background/dark-river-background.jpg)",
        }}
      >
        <Navigation />
        <Header
          props={JSON.stringify({
            title: "Cookie Policy",
            date: "15th August 2020",
          })}
        />
      </div>
      <article className="page-content block md:flex md:py-16 px-8 md:px-0">
        <div className="w-full md:w-2/3 md:p-8 py-8 text-lg" >
          <div className="w-full markdown">
            <h2 id="what-are-cookies">What are cookies?</h2>
            <p>
              Cookies are small text files which are downloaded to a user’s
              computer or mobile device when a browser is used to visit a
              website. Some cookies (known as sessional cookies) are created
              temporarily and are deleted when a user leaves a particular
              website. Other cookies (known as persistent cookies) allow the
              user’s device to be recognised by the originating website on
              subsequent visits to that website.
            </p>
            <p>
              Cookies are used to perform many different roles. For example they
              can be used to enable users to navigate between pages efficiently,
              remember their preferences, and manage log-ins and can be used to
              generally improve the user experience. They can also help to
              ensure that adverts displayed online are more relevant to users
              and their interests.
            </p>
            <p>
              As cookies themselves include very little information they cannot
              be used by themselves to identify users by name and cannot usually
              be used to reveal personal data.{" "}
            </p>
            <h3 id="how-we-use-cookies">How we use cookies</h3>
            <p>
              You can find more information about the types of cookies we use
              and the purposes for which we use them in the table below:{" "}
            </p>

            <h4>Category 1: Strictly Necessary Cookies</h4>
            <p>
              These cookies are necessary for the website to function correctly
              and to provide users with functions they specifically request
              (e.g. logging into a section of the website, selecting an item for
              the shopping basket, or filling in a form). These cookies can be
              disabled by changing your browser settings but some parts of the
              site will not then work.
            </p>
            <h4>Category 2: Analytics Cookies</h4>
            <p>
              These cookies allow us to count visits and traffic sources so we
              can measure and improve the performance of our site. They help us
              to know which pages are the most and least popular and see how
              visitors move around the site. These cookies don’t collect
              information that identifies a visitor’s name and our website uses
              IP anonymisation to truncate your IP address. All information that
              these cookies collect is aggregated and, therefore, anonymous. It
              is only used to improve how a website works.
            </p>
            <div className="flex">
              <div className="w-1/2">
                <h5>Cookie Name</h5>
                <p>
                  Universal Analytics (Google): <br />
                  _ga <br />
                  _gali <br />
                  _gat <br />
                  gid
                </p>
              </div>
              <div className="w-1/2">
                <h5>Purpose</h5>
                <p>
                  These cookies are used to collect information about how
                  visitors use our website. The data that is generated by the
                  cookie (including your IP Address) is forwarded to Google.
                  Google use this information to compile reports on our behalf
                  and to help us improve the website. This information informs
                  us about the number of visitors to the website, where visitors
                  have come to the website from and the pages they have visited.
                  [By default the _ga cookie expires 2 years from the date it
                  was last refreshed.
                </p>
              </div>
            </div>
            <h4 id="how-to-control-and-delete-cookies">
              How to control and delete cookies
            </h4>
            <p>
              Most web browsers allow some control of most cookies through the
              browser settings. To find out more about cookies, including how to
              see what cookies have been set, visit 
              <a href="www.aboutcookies.org" target="_blank" title="AboutCookies.org" className="underline">
                www.aboutcookies.org
              </a>
               or <br />
              <a href="ww.allaboutcookies.org" target="_blank" title="AllAboutCookies.org" className="underline">
                www.allaboutcookies.org
              </a>
              . To opt out of Google Analytics, you may install the Google
              Analytics Opt-Out Browser by visiting here{" "}
              <a href="http://tools.google.com/dlpage/gaoptout" target="_blank" title="Google Tools Opt Out" className="underline">Google Tools opt out</a>
              . Be aware that restricting all cookies via your browser settings
              may affect your ability to navigate and use our Website.
            </p>
            <div id="cicc-template"></div>
          </div>
        </div>
        <div data-aos="fade-right" className="w-full lg:w-1/3 p-4">
          <div className="hidden lg:block">
            <h5 className="text-2xl outline small b-100 uppercase pb-8 text-blur-heading">
              Navigation
            </h5>
            <a
              href="#what-are-cookies"
              title="What are cookies"
              className="block text-md"
            >
              What are cookies
            </a>
            <a
              href="#how-we-use-cookies"
              title="How we use cookies"
              className="block text-md"
            >
              How we use cookies
            </a>
            <a
              href="#how-to-control-and-delete-cookies"
              title="How to control and delete cookies"
              className="block text-md"
            >
              How to control and delete cookies
            </a>
          </div>
          <div className="hidden lg:block w-full my-8 h-1 bg-blue-gradient"></div>
          <LegalSidebarContact />
        </div>
      </article>
      <Footer />
      <MobileNavigation />
    </div>
  );
}
